export enum AccountError {
  ACCOUNT_ALREADY_EXISTS = 0,
  LOGIN_DETAILS_MISSING = 1,
  ACCOUNT_DOESNT_EXISTS = 2,
  AUTH_PARAM_INCORRECT = 3,
  INVALID_MAIL_FORMAT = 4,
  INVALID_PASSWORD = 5,
  VERF_ID_MISSING = 6,
  RESET_PARAMS_MISSING = 7,
  RESET_TOKEN_INVALID = 8,
  NEW_PASSWORD_IS_OLD = 9,
  TWITTER_AUTH_PARAMS_MISSING = 10,
  TWITTER_AUTH_FAILED = 11
}
