export enum AccountError {
  ACCOUNT_ALREADY_EXISTS = 0,
  LOGIN_DETAILS_MISSING = 1,
  ACCOUNT_DOESNT_EXISTS = 2,
  AUTH_PARAM_INCORRECT = 3,
  INVALID_MAIL_FORMAT = 4,
  VERF_ID_MISSING = 5,
  RESET_PARAMS_MISSING = 6
}
