export enum ClipError {
  ACCOUNT_ID_MISSING = 0,
  EPISODE_ID_MISSING = 1,
  CLIP_ID_MISSING = 2,
  CLIP_DATA_INCOMPLETE = 3,
  EPISODE_DOESNT_EXIST = 4,
  CLIP_TIMES_ARE_INCORRECT = 5,
  UPDATED_CLIP_DATA_MISSING = 6,
  CLIP_ID_INVALID = 7,
  CLIP_DATA_DOESNT_EXIST = 8
}
