export enum PodcastError {
  ACCOUNT_ID_MISSING = 0,
  PODCAST_ID_MISSING = 1,
  PODCAST_SRC_IDS_MISSING = 2,
  TOO_MANY_PODCAST_SRC_IDS = 3,
  EPISODE_IMPORT_DATA_INVALID = 4,
  EPISODE_IMPORT_TOKEN_INVALID = 5,
  PODCAST_IMPORT_SECRET_INVALID = 6,
  PODCAST_NOT_FOUND = 7,
  PODCAST_FOLLOW_ENTRY_NOT_FOUND = 8
}
